openapi: 3.0.2
info:
  title: auth-rest-api
  description: This is a basic JWT based auth API which supports user - signIn, signUp and refresh of user token.
  version: 1.0.0

servers:
  - url: "http://localhost:9001"

paths:
  /signup:
    post:
      tags:
        - User
      summary: enable user to register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        201:
          description: user created successfully
        404:
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
                example:
                  code: 404
                  message: "invalid password length"
        500:
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
                example:
                  code: 500
                  message: "not able to unmarshall request body"

  /signin:
    post:
      tags:
        - User
      summary: enable user to login and generate tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        201:
          description: user login successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignResp"
        404:
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
                example:
                  code: 404
                  message: "invalid password length"
        500:
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
                example:
                  code: 500
                  message: "not able to unmarshall request body"
                  
  /refresh:
    post:
      tags:
        - User
      summary: enable user to login and generate tokens
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/refreshToken"
      responses:
        201:
          description: user login successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignResp"
        404:
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
                example:
                  code: 404
                  message: "invalid password length"
        500:
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
                example:
                  code: 500
                  message: "not able to unmarshall request body"

  /revoke:
    post:
      tags:
        - User
      summary: enable user to login and generate tokens
      security:
        - bearerAuth : []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        201:
          description: user login successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignResp"
        404:
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
                example:
                  code: 404
                  message: "invalid password length"
        500:
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
                example:
                  code: 500
                  message: "not able to unmarshall request body"

  
components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          description: "a valid user email address"
          example: "sumit@kumar.com"
        password:
          type: string
          description: "a minimum of 8 character long password"
          example: "sumit@kumar"
      required:
        - email
        - password

    SignResp:
      type: object
      properties:
        email:
          type: string
          example: "sumit@kumar.com"
        accessToken:
          type: string
          example: ""
        refreshToken:
          type: string
          example: ""

    error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

    refreshToken:
      type: object
      properties:
        refreshToken:
          type: string
          example: ""

    healthResp:
      type: object
      properties:
        service:
          type: string
        database:
          type: string

  securitySchemes: 
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
